/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDo;

import view.MainScreen;

public class App {


    public static void main(String[] args) {
        MainScreen application = new MainScreen();
        application.setVisible(true);
       /*
        try {
            ProjectController projectController = new ProjectController();
            
            Project project = new Project();
            project.setName("Project teste");
            project.setDescription("description");
            
            projectController.save(project);
            
            project.setName("Novo nome do projeto");
            projectController.update(project);
            
            List<Project> projects = projectController.getAll();
            System.out.println("total de projetos " + projects.size());
            
            System.out.println(" funcionou ");
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }
}
